# Generated by Django 5.2.1 on 2025-06-10 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avatar", models.ImageField(upload_to="avatars/")),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("contact_no", models.CharField(max_length=15)),
                ("personal_email", models.EmailField(max_length=254)),
                ("nic_no", models.CharField(max_length=20)),
                ("guardian_name", models.CharField(max_length=100)),
                ("guardian_contact_no", models.CharField(max_length=15)),
                ("entry_year", models.IntegerField()),
                ("batch", models.CharField(max_length=20)),
                ("university_email", models.EmailField(max_length=254)),
                ("registration_no", models.CharField(max_length=20, unique=True)),
                (
                    "degree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="um_sys.degree"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="um_sys.department",
                    ),
                ),
            ],
        ),
    ]
