# Generated by Django 5.2.1 on 2025-06-11 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("um_sys", "0002_semester_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avatar", models.ImageField(upload_to="lecturer_avatars/")),
                ("name", models.CharField(max_length=100)),
                ("contact_no", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("university_id", models.CharField(max_length=20, unique=True)),
                ("qualification", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="LectureModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(max_length=20)),
                ("course_name", models.CharField(max_length=100)),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="um_sys.lecturer",
                    ),
                ),
            ],
        ),
    ]
