# Generated by Django 5.2.2 on 2025-06-15 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("um_sys", "0005_examresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="LectureMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_id", models.CharField(max_length=50)),
                ("course_id", models.CharField(max_length=20)),
                ("course_name", models.CharField(max_length=100)),
                ("topic", models.CharField(max_length=200)),
                ("sub_topic", models.CharField(blank=True, max_length=200)),
                ("note", models.TextField(blank=True)),
                ("document", models.FileField(upload_to="lecture_materials/")),
                ("deadline", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="um_sys.lecturer",
                    ),
                ),
            ],
        ),
    ]
