# Generated by Django 5.2.1 on 2025-06-22 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("um_sys", "0007_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(max_length=20)),
                ("course_name", models.CharField(max_length=100)),
                ("time_from", models.TimeField()),
                ("time_to", models.TimeField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="um_sys.lecturer",
                    ),
                ),
            ],
        ),
    ]
